### ISSUE TITLE
NullPointerException in opening custom tab

### ISSUE THREAD

**Issue by fantasy1022** [hitherejoe/Tabby#2]
When I click launch custom tab, APP would crash certainly.  It happens in HTC butterfly, but it work fine in Nexus 5.  The log is below: 

09-09 16:15:38.700 E/AndroidRuntime(14071): FATAL EXCEPTION: main
09-09 16:15:38.700 E/AndroidRuntime(14071): Process: com.hitherejoe.tabby, PID: 14071
09-09 16:15:38.700 E/AndroidRuntime(14071): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hitherejoe.tabby/com.hitherejoe.tabby.ui.activity.WebViewActivity}: java.lang.NullPointerException
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2596)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2653)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.app.ActivityThread.access$800(ActivityThread.java:156)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.os.Handler.dispatchMessage(Handler.java:102)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.os.Looper.loop(Looper.java:157)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.app.ActivityThread.main(ActivityThread.java:5872)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at java.lang.reflect.Method.invokeNative(Native Method)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at java.lang.reflect.Method.invoke(Method.java:515)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1069)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at dalvik.system.NativeStart.main(Native Method)
09-09 16:15:38.700 E/AndroidRuntime(14071): Caused by: java.lang.NullPointerException
09-09 16:15:38.700 E/AndroidRuntime(14071):     at com.hitherejoe.tabby.ui.activity.WebViewActivity.onCreate(WebViewActivity.java:26)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.app.Activity.performCreate(Activity.java:5312)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
09-09 16:15:38.700 E/AndroidRuntime(14071):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2552)
09-09 16:15:38.700 E/AndroidRuntime(14071):     ... 11 more

**Comment by hitherejoe** [comment]
Thanks for pointing that out! Stupid mistake on my behalf, should be fixed now :+1:
