### ISSUE TITLE
WebViewActivity, if not callable?

### ISSUE THREAD

**Issue by TouchBoarder** [hitherejoe/Tabby#5]
Suggestion:
In the Fallback class do a check if the WebViewActivity is callable else open the url (Uri) with a standard action view intent:

```
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setData(uri);
        activity.startActivity(i);
```

**Comment by hitherejoe** [comment]
Thanks for the suggestion but I don't really feel that this is an issue? Currently I'm using:

`Intent intent = new Intent(activity, WebViewActivity.class);
intent.putExtra(WebViewActivity.EXTRA_URL, uri.toString());`

and then calling startActivity(); I guess it would be easier to just start a View intent, but having the WebView activity as part of my project is a preference for me. It also gives a bit more control if changes are needed in the future!
